version: "3.8"
services:
  cache:
    image: redis:6.2-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  go-api:
    image: golang
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=cache:6379
    volumes:
      - ${PWD}/:/api
    working_dir: /api
    command: go run main.go
